services:
  postgres-identity:
    image: postgres:15
    environment:
      POSTGRES_DB: identity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  postgres-crm:
    image: postgres:15
    environment:
      POSTGRES_DB: crm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  identity-service:
    build: ./services/identity-service
    volumes:
      - ./services/identity-service:/app
    depends_on:
      - postgres-identity
    ports:
      - "8001:8000"

  crm-service:
    build: ./services/crm-service
    volumes:
      - ./services/crm-service:/app
    depends_on:
      - postgres-crm
      - kafka
    ports:
      - "8002:8000"
  crm-worker:
    build: ./services/crm-service
    volumes:
      - ./services/crm-service:/app
    command: ["python", "worker.py"]
    depends_on:
      - kafka
      - postgres-crm
